# Generated by Django 4.0.2 on 2022-08-15 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DiaryApp', '0002_question365'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question365',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
