# Generated by Django 4.0.2 on 2022-08-15 14:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('DiaryApp', '0004_alter_question365_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Answer365',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.TextField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DiaryApp.question365')),
            ],
        ),
    ]
