# Generated by Django 4.0.6 on 2022-08-18 15:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('DiaryApp', '0006_answer365_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer365',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
