# Generated by Django 4.0.2 on 2022-08-19 05:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DiaryApp', '0008_alter_answer365_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer365',
            name='user',
        ),
    ]
